### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [RLLD576/Rober-Carpet#3]

**Comment by RLLD576** [comment]
I'll work on that soon.
In what rule/s are you interested in?

**Comment by sternschnaube** [comment]
sleeping delay is great 😄

**Comment by RLLD576** [comment]
Right now I'm working on implementing a gradle plugin for a better version management, this will be better in the long term but will delay the update. With this system, it will be easier in the future to maintain all the versions that will come.

**Comment by sternschnaube** [comment]
Thank you for the fast update 😊
